#python 2022/9/5

# 异常

## 目标

- 异常的概念
- 捕获异常
- 异常的传递
- 自定义异常

## 01.异常的概念

- 程序在运行时，如果 `Python 解释器` 遇到一个错误，**会停止程序的执行，并且提示一些错误信息**，这就是**异常**
- 程序停止执行并且提示错误信息这个动作，我们通常称之为：**抛出(raise)异常**

>程序开发时，很难将所有的特殊情况都处理的面面俱到，通过**异常捕获**可以针对突发事件做集中的处理，从而保证程序的稳定性和健壮性

## 02.捕获异常

### 2.1 简单的捕获异常语法

- 在程序开发中，如果对某些代码的执行不能确定是否正确，可以增加 `try(尝试)` 来捕获异常
- 捕获异常最简单的语法格式：

```python
try:
	尝试执行的代码
except:
	出现错误的处理
```

- `try` 尝试，下方编写要尝试的代码，不确定是否能够正常执行的代码
- `except` 如果不是，下方编写尝试失败的代码

**简单异常捕获演练 -- 眼球用户输入整数**

```python
try:
    # 不能确定正确执行的代码
    num = int(input("请输入一个整数："))
except:
    # 错误的处理代码
    print("请输入正确的整数格式")

print("-" * 50)
```

### 2.2 错误类型的捕获

- 在程序执行时，可能会遇到不同类型的异常，并且需要**针对不同类型的异常，做出不同的响应，这个时候，就需要捕获错误类型**
- 语法如下：

```python
try:
	# 尝试执行的代码
	pass
except 错误类型1:
	# 针对错误类型1，对应的代码处理
	pass
except (错误类型2, 错误类型3):
	# 针对错误类型2 和 3，对应的代码处理
	pass
except Exception as result:
	print("未知错误 %s " % result)
```

- 当 `Python` **解释器抛出异常时，最后一行错误信息的第一个单词，就是错误类型**

**需求**

1. 提示用户输入一个整数
2. 使用 `8` 除以用户输入的整数并且输出

```python
try:
    # 1. 提示用户输入一个整数
    num = int(input("输入一个整数："))

    # 2. 使用 `8` 除以用户输入的整数并且输出
    res = 8 / num

    print(res)
except ZeroDivisionError:
    print("除0错误")
except ValueError:
    print("请输入正确的整数")
```

**捕获未知错误**

- 在开发时，要预判到所有可能出现的错误，还是有一定难度的
- 如果希望程序无论出现任何错误，都不会因为 `Python` 解释器抛出异常而被终止，可以再增加一个 `except`
- 语法如下：

```python
except Exception as result:
	print("未知错误 %s" % result)
```

### 2.3 异常捕获完整语法

- 在实际开发中，为了能够处理复杂的异常情况，实际的异常语法如下：

>提示：
>- 有关完整语法的应用场景，在后续学习中，结合实际的案例会更好理解

```python
try:
	# 尝试执行的代码
	pass
except 错误类型1:
	# 针对错误类型1，对应的代码处理
	pass
except 错误类型2:
	# 针对错误类型2，对应的代码处理
	pass
except (错误类型3, 错误类型4):
	# 针对错误类型3 和 4，对应的d代码处理
	pass
except Exception as result:
	# 打印错误信息
	print(result)
else:
	# 没有异常才会执行的代码
	pass
finally:
	# 无论是否有异常，都会执行的代码
	print("无论是否有异常，都会执行的代码")
```

- `else` 只有在没有异常时才会执行的代码
- `finally` 无论是否有异常，都会执行的代码
- 之前一个演练的完整捕获异常代码如下：

```python
try:
    # 1. 提示用户输入一个整数
    num = int(input("输入一个整数："))

    # 2. 使用 `8` 除以用户输入的整数并且输出
    res = 8 / num

    print(res)
except ValueError:
    print("请输入正确的整数")
except Exception as result:
    print("未知错误 %s" % result)
else:
    print("尝试成功")
finally:
    print("无论是否出现异常都会执行的代码")

print("-" * 20)
```

## 03.异常的传递

- 异常的传递 -- 当函数/方法执行出现异常，会将异常传递给函数/方法的调用一方
- 如果传递到主程序，仍然没有异常处理，程序才会被终止
- 在开发中，可以在主函数中增加异常捕获
- 而在主函数中国调用的其他函数，只要出现异常，都会传递到主函数的异常捕获中
- 这样就不需要在代码中，增加大量的异常捕获，能够保证代码的整洁

**需求**

1. 定义函数 `demo1()` **提示用户输入一个函数并且返回**
2. 定义函数 `demo2()` 调用 `demo1()`
3. 在 主程序中调用 `demo2()`

```python
def demo1():
    return int(input("请输入整数："))


def demo2():
    return demo1()

# 利用异常的传递性，在主程序捕获异常
try:
    print(demo2())
except Exception as result:
    print("未知错误 %s" % result)
```

## 04.抛出 raise 异常

### 4.1 应用场景

- 在开发中，除了代码执行出错 `python` 解释器会抛出异常之外
- 还可以**根据应用程序特有的业务需求主动抛出异常**

**示例**

- 提示用户输入密码，如果长度少于8，抛出异常

![自定义异常](img/img46.png)

**注意**

- 当前函数只负责提示用户输入密码，如果密码长度不正确，需要其他函数进行额外处理
- 因此可以抛出异常，由其他需要处理的函数捕获异常

```python

```

### 4.2 抛出异常

- 在 Python 中提供了一个 `Exception` 异常类
- 在开发时，如果满足特定业务需求时，希望抛出异常，可以：
	1. **创建一个 `Exception` 的对象**
	2. **使用 `raise` 关键字抛出异常对象**

**需求**

- 定义 `inpyt_password` 函数，提示用户输入密码
- 如果用户输入长度 <8，抛出异常
- 如果用户输入长度 >= 8，返回输入的密码

```python
def input_password():

    # 1.提示用户输入密码
    pwd = input("请输入密码：")
    # 2.判断密码长度 >= 8，返回用户输入的密码
    if len(pwd) >= 8:
        return pwd
    # 3.如果 < 8，主动抛出异常
    print("主动抛出异常")
    # 1>创建异常对象 - 可以使用错误信息字符串作为参数
    ex = Exception("密码长度不够")
    # 2>主动抛出异常
    raise ex


# 提示用户输入密码
try:
    print(input_password())
except Exception as result:
    print(result)
```